#!/usr/bin/env node
/*
 Installs a post-commit git hook that runs the version update script.
 This script is intended to run from the repository root.
*/
const fs = require('fs');
const path = require('path');

function main() {
  try {
    const repoRoot = process.cwd();
    const gitDir = path.join(repoRoot, '.git');
    const hooksDir = path.join(gitDir, 'hooks');

    if (!fs.existsSync(gitDir)) {
      console.log('No .git directory found. Skipping git hooks installation.');
      return;
    }
    if (!fs.existsSync(hooksDir)) {
      fs.mkdirSync(hooksDir, { recursive: true });
    }

    const postCommitPath = path.join(hooksDir, 'post-commit');
    const script = `#!/bin/sh\n\n# Auto-generated by scripts/install-hooks.js\nnode \'front-end/scripts/update-version.js\'\n`;

    fs.writeFileSync(postCommitPath, script, { mode: 0o755 });
    console.log('Installed post-commit hook to update version number.');
  } catch (e) {
    console.error('Failed to install git hooks:', e.message);
  }
}

main();
